/*
 * SPDX-FileCopyrightText: 2024 Roland Rusch, easy-smart solution GmbH <roland.rusch@easy-smart.ch>
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef LIBSMART_STM32SHELL_LIBSMART_CONFIG_DIST_HPP
#define LIBSMART_STM32SHELL_LIBSMART_CONFIG_DIST_HPP


#define LIBSMART_STM32SHELL

#define LIBSMART_STM32SHELL_MICRORLSTREAMSESSION_BUFFER_SIZE_RX 256
#define LIBSMART_STM32SHELL_MICRORLSTREAMSESSION_BUFFER_SIZE_TX 256


#endif
